### ISSUE TITLE
Can't build EIF from Docker image with `apt-get install snapd`

### ISSUE THREAD

**Issue by open-contracts** [aws/aws-nitro-enclaves-cli#306]
Docker successfully builds an image from a Dockerfile containing `apt-get install snapd`. But `nitro-cli build-enclave` fails, raising:

```
Using the locally available Docker image...
Linuxkit reported an error while creating the customer ramfs: "Add init containers:\nProcess init image: docker.io/library/image\nAdd files:\n  rootfs/dev\n  rootfs/run\n  rootfs/sys\n  rootfs/var\n  rootfs/proc\n  rootfs/tmp\n  cmd\n  env\nCreate outputs:\nfatal error: runtime: out of memory\n\nruntime stack:\nruntime.throw(0x7fdff6f1f812, 0x16)\n\t/usr/lib/go/src/runtime/panic.go:608 +0x74\nruntime.sysMap(0xc098000000, 0x84000000, 0x7fdff8bb4c98)\n\t/usr/lib/go/src/runtime/mem_linux.go:156 +0xc9\nruntime.(*mheap).sysAlloc(0x7fdff8b9a120, 0x84000000, 0x116bb8, 0x7fdff1697cd0)\n\t/usr/lib/go/src/runtime/malloc.go:619 +0x1c9\nruntime.(*mheap).grow(0x7fdff8b9a120, 0x41189, 0x0)\n\t/usr/lib/go/src/runtime/mheap.go:920 +0x44\nruntime.(*mheap).allocSpanLocked(0x7fdff8b9a120, 0x41189, 0x7fdff8bb4ca8, 0x20301300000000)\n\t/usr/lib/go/src/runtime/mheap.go:848 +0x339\nruntime.(*mheap).alloc_m(0x7fdff8b9a120, 0x41189, 0xffffffffffff0101, 0x7fdff1697d88)\n\t/usr/lib/go/src/runtime/mheap.go:692 +0x11d\nruntime.(*mheap).alloc.func1()\n\t/usr/lib/go/src/runtime/mheap.go:759 +0x4e\nruntime.(*mheap).alloc(0x7fdff8b9a120, 0x41189, 0x7fdff1010101, 0x7fdff5f89a99)\n\t/usr/lib/go/src/runtime/mheap.go:758 +0x8c\nruntime.largeAlloc(0x82310763, 0x7fdff5fc0101, 0x7fdff5259000)\n\t/usr/lib/go/src/runtime/malloc.go:1019 +0x99\nruntime.mallocgc.func1()\n\t/usr/lib/go/src/runtime/malloc.go:914 +0x48\nruntime.systemstack(0x0)\n\t/usr/lib/go/src/runtime/asm_amd64.s:351 +0x63\nruntime.mstart()\n\t/usr/lib/go/src/runtime/proc.go:1229\n\ngoroutine 1 [running]:\nruntime.systemstack_switch()\n\t/usr/lib/go/src/runtime/asm_amd64.s:311 fp=0xc00055ad20 sp=0xc00055ad18 pc=0x7fdff5fca530\nruntime.mallocgc(0x82310763, 0x7fdff74f4b60, 0xc04d62c001, 0xc00055adf8)\n\t/usr/lib/go/src/runtime/malloc.go:913 +0x8a8 fp=0xc00055adc0 sp=0xc00055ad20 pc=0x7fdff5f7f718\nruntime.makeslice(0x7fdff74f4b60, 0x82310763, 0x82310763, 0xc00055ae50, 0x7fdff5f9e463, 0x7fdff799f908)\n\t/usr/lib/go/src/runtime/slice.go:70 +0x79 fp=0xc00055adf0 sp=0xc00055adc0 pc=0x7fdff5fb53d9\nbytes.makeSlice(0x82310763, 0x0, 0x0, 0x0)\n\t/usr/lib/go/src/bytes/buffer.go:231 +0x6f fp=0xc00055ae30 sp=0xc00055adf0 pc=0x7fdff607238f\nbytes.(*Buffer).grow(0xc00013c1c0, 0x763, 0x0)\n\t/usr/lib/go/src/bytes/buffer.go:144 +0x16e fp=0xc00055ae80 sp=0xc00055ae30 pc=0x7fdff6071cde\nbytes.(*Buffer).Write(0xc00013c1c0, 0xc04d62c000, 0x763, 0x8000, 0x763, 0x0, 0x0)\n\t/usr/lib/go/src/bytes/buffer.go:174 +0xe7 fp=0xc00055aeb0 sp=0xc00055ae80 pc=0x7fdff6071fd7\ngithub.com/linuxkit/linuxkit/src/cmd/linuxkit/pad4.Writer.Write(0x7fdff79aa1a0, 0xc00013c1c0, 0x0, 0xc04d62c000, 0x763, 0x8000, 0x0, 0x0, 0x7fdff5259000)\n\t/go/src/github.com/linuxkit/linuxkit/src/cmd/linuxkit/pad4/pad4.go:16 +0x55 fp=0xc00055aef8 sp=0xc00055aeb0 pc=0x7fdff6589bc5\ngithub.com/linuxkit/linuxkit/src/cmd/linuxkit/pad4.(*Writer).Write(0xc0003d1680, 0xc04d62c000, 0x763, 0x8000, 0xc00055afd0, 0xc00055afd8, 0x8001)\n\t<autogenerated>:1 +0x76 fp=0xc00055af50 sp=0xc00055aef8 pc=0x7fdff6589fe6\ngithub.com/linuxkit/linuxkit/src/cmd/linuxkit/vendor/github.com/surma/gocpio.(*Writer).countedWrite(0xc00037a360, 0xc04d62c000, 0x763, 0x8000, 0xc00055b018, 0x7fdff637457d, 0x7fdff79aa520)\n\t/go/src/github.com/linuxkit/linuxkit/src/cmd/linuxkit/vendor/github.com/surma/gocpio/writer.go:105 +0x53 fp=0xc00055af98 sp=0xc00055af50 pc=0x7fdff658a973\ngithub.com/linuxkit/linuxkit/src/cmd/linuxkit/vendor/github.com/surma/gocpio.(*Writer).Write(0xc00037a360, 0xc04d62c000, 0x763, 0x8000, 0x763, 0x7fdff79aa520, 0xc00009a030)\n\t/go/src/github.com/linuxkit/linuxkit/src/cmd/linuxkit/vendor/github.com/surma/gocpio/writer.go:99 +0x5d fp=0xc00055afe0 sp=0xc00055af98 pc=0x7fdff658a8cd\ngithub.com/linuxkit/linuxkit/src/cmd/linuxkit/initrd.(*Writer).Write(0xc000244300, 0xc04d62c000, 0x763, 0x8000, 0x763, 0x7fdff79aa520, 0xc00009a030)\n\t/go/src/github.com/linuxkit/linuxkit/src/cmd/linuxkit/initrd/initrd.go:168 +0x4f fp=0xc00055b028 sp=0xc00055afe0 pc=0x7fdff658bb3f\nio.copyBuffer(0x7fdff79aa560, 0xc000244300, 0x7fdff79aa080, 0xc0000c6480, 0xc04d62c000, 0x8000, 0x8000, 0xc00055b150, 0x0, 0x0)\n\t/usr/lib/go/src/io/io.go:404 +0x203 fp=0xc00055b098 sp=0xc00055b028 pc=0x7fdff5fd6ce3\nio.Copy(0x7fdff79aa560, 0xc000244300, 0x7fdff79aa080, 0xc0000c6480, 0x0, 0x0, 0x2)\n\t/usr/lib/go/src/io/io.go:364 +0x5c fp=0xc00055b0f8 sp=0xc00055b098 pc=0x7fdff5fd69ac\ngithub.com/linuxkit/linuxkit/src/cmd/linuxkit/initrd.copyTarEntry(0xc000244300, 0xc04d573c00, 0x7fdff79aa080, 0xc0000c6480, 0x15, 0x0, 0x0)\n\t/go/src/github.com/linuxkit/linuxkit/src/cmd/linuxkit/initrd/initrd.go:87 +0x28d fp=0xc00055b1b0 sp=0xc00055b0f8 pc=0x7fdff658b1ed\ngithub.com/linuxkit/linuxkit/src/cmd/linuxkit/initrd.CopySplitTar(0xc000244300, 0xc0000c6480, 0x1, 0x7fdff2f91c90, 0x7fdff5fc79b0, 0xc00055b2b0, 0xc00055b2c0, 0x10, 0x7fdff75f0700, 0x7fdff75f0700, ...)\n\t/go/src/github.com/linuxkit/linuxkit/src/cmd/linuxkit/initrd/initrd.go:144 +0x1d4 fp=0xc00055b250
sp=0xc00055b1b0 pc=0x7fdff658b484\ngithub.com/linuxkit/linuxkit/src/cmd/linuxkit/moby.tarToInitrd(0x7fdff79ad760, 0xc00000e020, 0x7fdff603da31, 0xc000230d70, 0xc000000300, 0xc0000ba0a0, 0x7fdff5f85473, 0x7fdff6f0a332, 0x7ffc35258673, 0xd, ...)\n\t/go/src/github.com/linuxkit/linuxkit/src/cmd/linuxkit/moby/output.go:272 +0x1cb fp=0xc00055b340 sp=0xc00055b250 pc=0x7fdff65a2fbb\ngithub.com/linuxkit/linuxkit/src/cmd/linuxkit/moby.glob..func2(0xc0000400f0, 0x2d, 0x7fdff79ad760, 0xc00000e020, 0x400, 0x1, 0xc00055b460, 0x7fdff60682a1)\n\t/go/src/github.com/linuxkit/linuxkit/src/cmd/linuxkit/moby/output.go:48 +0x4f fp=0xc00055b3e8 sp=0xc00055b340 pc=0x7fdff65a86ef\ngithub.com/linuxkit/linuxkit/src/cmd/linuxkit/moby.Formats(0xc0000400f0, 0x2d, 0xc000230d70, 0xe, 0xc00009b380, 0x1, 0x1, 0x400, 0x1, 0x0, ...)\n\t/go/src/github.com/linuxkit/linuxkit/src/cmd/linuxkit/moby/output.go:260 +0x29a fp=0xc00055b4a8 sp=0xc00055b3e8 pc=0x7fdff65a2d0a\nmain.build(0xc0000b8020, 0x7, 0x7)\n\t/go/src/github.com/linuxkit/linuxkit/src/cmd/linuxkit/build.go:220 +0x116c fp=0xc00055bf00 sp=0xc00055b4a8 pc=0x7fdff6eb036c\nmain.main()\n\t/go/src/github.com/linuxkit/linuxkit/src/cmd/linuxkit/main.go:121 +0x417 fp=0xc00055bf98 sp=0xc00055bf00 pc=0x7fdff6eb6127\nruntime.main()\n\t/usr/lib/go/src/runtime/proc.go:201 +0x20f fp=0xc00055bfe0 sp=0xc00055bf98 pc=0x7fdff5fa082f\nruntime.goexit()\n\t/usr/lib/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc00055bfe8 sp=0xc00055bfe0 pc=0x7fdff5fcc641\n\ngoroutine 19 [syscall]:\nos/signal.signal_recv(0x0)\n\t/usr/lib/go/src/runtime/sigqueue.go:139 +0x9e\nos/signal.loop()\n\t/usr/lib/go/src/os/signal/signal_unix.go:23 +0x24\ncreated by os/signal.init.0\n\t/usr/lib/go/src/os/signal/signal_unix.go:29 +0x43\n\ngoroutine 25 [IO wait]:\ninternal/poll.runtime_pollWait(0x7fdff2f91f00, 0x72, 0xc000064a88)\n\t/usr/lib/go/src/runtime/netpoll.go:173 +0x68\ninternal/poll.(*pollDesc).wait(0xc000266418, 0x72, 0xffffffffffffff00, 0x7fdff79affe0, 0x7fdff8b3eac0)\n\t/usr/lib/go/src/internal/poll/fd_poll_runtime.go:85 +0x9c\ninternal/poll.(*pollDesc).waitRead(0xc000266418, 0xc000246000, 0x1000, 0x1000)\n\t/usr/lib/go/src/internal/poll/fd_poll_runtime.go:90 +0x3f\ninternal/poll.(*FD).Read(0xc000266400, 0xc000246000, 0x1000, 0x1000,
0x0, 0x0, 0x0)\n\t/usr/lib/go/src/internal/poll/fd_unix.go:169 +0x17b\nnet.(*netFD).Read(0xc000266400, 0xc000246000, 0x1000, 0x1000, 0xc000064b70, 0x7fdff5fc91f0, 0xc000000300)\n\t/usr/lib/go/src/net/fd_unix.go:202 +0x51\nnet.(*conn).Read(0xc0000b2a40, 0xc000246000, 0x1000, 0x1000, 0x0, 0x0, 0x0)\n\t/usr/lib/go/src/net/net.go:177 +0x6a\nnet/http.(*persistConn).Read(0xc00041d7a0, 0xc000246000, 0x1000, 0x1000, 0xc000064c70, 0x7fdff5f78335, 0xc00008a4e0)\n\t/usr/lib/go/src/net/http/transport.go:1497 +0x77\nbufio.(*Reader).fill(0xc00026ff20)\n\t/usr/lib/go/src/bufio/bufio.go:100 +0x111\nbufio.(*Reader).Peek(0xc00026ff20, 0x1, 0x0, 0x0, 0x1, 0xc00008a420, 0x0)\n\t/usr/lib/go/src/bufio/bufio.go:132 +0x41\nnet/http.(*persistConn).readLoop(0xc00041d7a0)\n\t/usr/lib/go/src/net/http/transport.go:1645 +0x1a4\ncreated by net/http.(*Transport).dialConn\n\t/usr/lib/go/src/net/http/transport.go:1338 +0x943\n\ngoroutine 26 [select]:\nnet/http.(*persistConn).writeLoop(0xc00041d7a0)\n\t/usr/lib/go/src/net/http/transport.go:1885 +0x115\ncreated by net/http.(*Transport).dialConn\n\t/usr/lib/go/src/net/http/transport.go:1339 +0x968\n\ngoroutine 28 [IO wait]:\ninternal/poll.runtime_pollWait(0x7fdff2f91e30, 0x72, 0xc000065a88)\n\t/usr/lib/go/src/runtime/netpoll.go:173 +0x68\ninternal/poll.(*pollDesc).wait(0xc000266898, 0x72, 0xffffffffffffff00, 0x7fdff79affe0, 0x7fdff8b3eac0)\n\t/usr/lib/go/src/internal/poll/fd_poll_runtime.go:85 +0x9c\ninternal/poll.(*pollDesc).waitRead(0xc000266898, 0xc0000ca000, 0x1000, 0x1000)\n\t/usr/lib/go/src/internal/poll/fd_poll_runtime.go:90 +0x3f\ninternal/poll.(*FD).Read(0xc000266880, 0xc0000ca000, 0x1000, 0x1000, 0x0, 0x0, 0x0)\n\t/usr/lib/go/src/internal/poll/fd_unix.go:169 +0x17b\nnet.(*netFD).Read(0xc000266880, 0xc0000ca000, 0x1000, 0x1000, 0xc000065b70, 0x7fdff5fc91f0, 0xc000000300)\n\t/usr/lib/go/src/net/fd_unix.go:202 +0x51\nnet.(*conn).Read(0xc0000b2a78, 0xc0000ca000, 0x1000, 0x1000, 0x0, 0x0, 0x0)\n\t/usr/lib/go/src/net/net.go:177 +0x6a\nnet/http.(*persistConn).Read(0xc00041d9e0, 0xc0000ca000, 0x1000, 0x1000, 0xc000065c70, 0x7fdff5f78335, 0xc00008aa20)\n\t/usr/lib/go/src/net/http/transport.go:1497 +0x77\nbufio.(*Reader).fill(0xc00001a2a0)\n\t/usr/lib/go/src/bufio/bufio.go:100 +0x111\nbufio.(*Reader).Peek(0xc00001a2a0, 0x1, 0x0, 0x0, 0x1, 0xc00008a960, 0x0)\n\t/usr/lib/go/src/bufio/bufio.go:132 +0x41\nnet/http.(*persistConn).readLoop(0xc00041d9e0)\n\t/usr/lib/go/src/net/http/transport.go:1645 +0x1a4\ncreated by net/http.(*Transport).dialConn\n\t/usr/lib/go/src/net/http/transport.go:1338 +0x943\n\ngoroutine 29 [select]:\nnet/http.(*persistConn).writeLoop(0xc00041d9e0)\n\t/usr/lib/go/src/net/http/transport.go:1885 +0x115\ncreated by net/http.(*Transport).dialConn\n\t/usr/lib/go/src/net/http/transport.go:1339 +0x968\n\ngoroutine 31 [IO wait]:\ninternal/poll.runtime_pollWait(0x7fdff2f91d60, 0x72, 0xc000069a88)\n\t/usr/lib/go/src/runtime/netpoll.go:173 +0x68\ninternal/poll.(*pollDesc).wait(0xc00033a318, 0x72, 0xffffffffffffff00, 0x7fdff79affe0, 0x7fdff8b3eac0)\n\t/usr/lib/go/src/internal/poll/fd_poll_runtime.go:85 +0x9c\ninternal/poll.(*pollDesc).waitRead(0xc00033a318, 0xc000270000, 0x1000, 0x1000)\n\t/usr/lib/go/src/internal/poll/fd_poll_runtime.go:90 +0x3f\ninternal/poll.(*FD).Read(0xc00033a300, 0xc000270000, 0x1000, 0x1000, 0x0, 0x0, 0x0)\n\t/usr/lib/go/src/internal/poll/fd_unix.go:169 +0x17b\nnet.(*netFD).Read(0xc00033a300, 0xc000270000, 0x1000, 0x1000, 0x1, 0x0, 0x7fdff6eff010)\n\t/usr/lib/go/src/net/fd_unix.go:202 +0x51\nnet.(*conn).Read(0xc0000b2048, 0xc000270000, 0x1000, 0x1000, 0x0, 0x0, 0x0)\n\t/usr/lib/go/src/net/net.go:177 +0x6a\nnet/http.(*persistConn).Read(0xc00041c000, 0xc000270000, 0x1000, 0x1000, 0xc00007fe60, 0xc00041c000, 0x0)\n\t/usr/lib/go/src/net/http/transport.go:1497 +0x77\nbufio.(*Reader).fill(0xc00026e1e0)\n\t/usr/lib/go/src/bufio/bufio.go:100 +0x111\nbufio.(*Reader).Peek(0xc00026e1e0, 0x1, 0x2, 0x0, 0x0, 0xc00008a660, 0x0)\n\t/usr/lib/go/src/bufio/bufio.go:132 +0x41\nnet/http.(*persistConn).readLoop(0xc00041c000)\n\t/usr/lib/go/src/net/http/transport.go:1645 +0x1a4\ncreated by net/http.(*Transport).dialConn\n\t/usr/lib/go/src/net/http/transport.go:1338 +0x943\n\ngoroutine 32 [select]:\nnet/http.(*persistConn).writeLoop(0xc00041c000)\n\t/usr/lib/go/src/net/http/transport.go:1885 +0x115\ncreated by net/http.(*Transport).dialConn\n\t/usr/lib/go/src/net/http/transport.go:1339 +0x968\n"
[ E48 ] EIF building error. Such error appears when trying to build an EIF file. In this case, the error backtrace provides detailed information on the failure reason.

For more details, please visit https://docs.aws.amazon.com/enclaves/latest/user/cli-errors.html#E48
```

Any idea how to fix this? I'm expecting that it won't be easy to get snap run inside the enclave, but it would unlock a powerful usecase for me so I want to take a shot at it

**Comment by alcioa** [comment]
@open-contracts is this issue still relevant?
