### ISSUE TITLE
Cant build from Dockerimage with `pip install PySide2`

### ISSUE THREAD

**Issue by Jonas-Metzger** [aws/aws-nitro-enclaves-cli#309]
What does this error mean? Trying to build an image containing the `PySide2` pip package. Same issue with `PyQt5`.
```
Start building the Enclave Image...
Using the locally available Docker image...
Linuxkit reported an error while creating the customer ramfs: "Add init containers:
Process init image: docker.io/library/image
Add files:
  rootfs/dev
  rootfs/run
  rootfs/sys
  rootfs/var
  rootfs/proc
  rootfs/tmp
  cmd
  env
Create outputs:
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x7f0046618812, 0x16)
	/usr/lib/go/src/runtime/panic.go:608 +0x74
runtime.sysMap(0xc098000000, 0x84000000, 0x7f00482adc98)
	/usr/lib/go/src/runtime/mem_linux.go:156 +0xc9
runtime.(*mheap).sysAlloc(0x7f0048293120, 0x84000000, 0xa00053fe98, 0x7f0042497cd0)
	/usr/lib/go/src/runtime/malloc.go:619 +0x1c9
runtime.(*mheap).grow(0x7f0048293120, 0x4118c, 0x0)
	/usr/lib/go/src/runtime/mheap.go:920 +0x44
runtime.(*mheap).allocSpanLocked(0x7f0048293120, 0x4118c, 0x7f00482adca8, 0x20302200000000)
	/usr/lib/go/src/runtime/mheap.go:848 +0x339
runtime.(*mheap).alloc_m(0x7f0048293120, 0x4118c, 0xffffffffffff0101, 0x7f0042497d88)
	/usr/lib/go/src/runtime/mheap.go:692 +0x11d
runtime.(*mheap).alloc.func1()
	/usr/lib/go/src/runtime/mheap.go:759 +0x4e
runtime.(*mheap).alloc(0x7f0048293120, 0x4118c, 0x7f0042010101, 0x7f0045682a99)
	/usr/lib/go/src/runtime/mheap.go:758 +0x8c
runtime.largeAlloc(0x82318000, 0x7f00456c0101, 0x7f00449526c0)
	/usr/lib/go/src/runtime/malloc.go:1019 +0x99
runtime.mallocgc.func1()
	/usr/lib/go/src/runtime/malloc.go:914 +0x48
runtime.systemstack(0x0)
	/usr/lib/go/src/runtime/asm_amd64.s:351 +0x63
runtime.mstart()
	/usr/lib/go/src/runtime/proc.go:1229

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/lib/go/src/runtime/asm_amd64.s:311 fp=0xc000648d20 sp=0xc000648d18 pc=0x7f00456c3530
runtime.mallocgc(0x82318000, 0x7f0046bedb60, 0xc08bcfc001, 0xc000648df8)
	/usr/lib/go/src/runtime/malloc.go:913 +0x8a8 fp=0xc000648dc0 sp=0xc000648d20 pc=0x7f0045678718
runtime.makeslice(0x7f0046bedb60, 0x82318000, 0x82318000, 0xc000648e50, 0x7f0045697463, 0x7f0047098908)
	/usr/lib/go/src/runtime/slice.go:70 +0x79 fp=0xc000648df0 sp=0xc000648dc0 pc=0x7f00456ae3d9
bytes.makeSlice(0x82318000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/bytes/buffer.go:231 +0x6f fp=0xc000648e30 sp=0xc000648df0 pc=0x7f004576b38f
bytes.(*Buffer).grow(0xc00013c1c0, 0x8000, 0x0)
	/usr/lib/go/src/bytes/buffer.go:144 +0x16e fp=0xc000648e80 sp=0xc000648e30 pc=0x7f004576acde
bytes.(*Buffer).Write(0xc00013c1c0, 0xc08bcfc000, 0x8000, 0x8000, 0x8000,
0x0, 0x0)
	/usr/lib/go/src/bytes/buffer.go:174 +0xe7 fp=0xc000648eb0 sp=0xc000648e80 pc=0x7f004576afd7
github.com/linuxkit/linuxkit/src/cmd/linuxkit/pad4.Writer.Write(0x7f00470a31a0, 0xc00013c1c0, 0x0, 0xc08bcfc000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/go/src/github.com/linuxkit/linuxkit/src/cmd/linuxkit/pad4/pad4.go:16 +0x55 fp=0xc000648ef8 sp=0xc000648eb0 pc=0x7f0045c82bc5
github.com/linuxkit/linuxkit/src/cmd/linuxkit/pad4.(*Writer).Write(0xc00026c020, 0xc08bcfc000, 0x8000, 0x8000, 0xc08bcfc000, 0x8000, 0x8000)
	<autogenerated>:1 +0x76 fp=0xc000648f50 sp=0xc000648ef8 pc=0x7f0045c82fe6
github.com/linuxkit/linuxkit/src/cmd/linuxkit/vendor/github.com/surma/gocpio.(*Writer).countedWrite(0xc000443ef0, 0xc08bcfc000, 0x8000, 0x8000, 0xc000649018, 0x7f0045a6d4df, 0xc08bb9fe00)
	/go/src/github.com/linuxkit/linuxkit/src/cmd/linuxkit/vendor/github.com/surma/gocpio/writer.go:105 +0x53 fp=0xc000648f98 sp=0xc000648f50 pc=0x7f0045c83973
github.com/linuxkit/linuxkit/src/cmd/linuxkit/vendor/github.com/surma/gocpio.(*Writer).Write(0xc000443ef0, 0xc08bcfc000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
	/go/src/github.com/linuxkit/linuxkit/src/cmd/linuxkit/vendor/github.com/surma/gocpio/writer.go:99 +0x5d fp=0xc000648fe0 sp=0xc000648f98 pc=0x7f0045c838cd
github.com/linuxkit/linuxkit/src/cmd/linuxkit/initrd.(*Writer).Write(0xc0001a8270, 0xc08bcfc000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
	/go/src/github.com/linuxkit/linuxkit/src/cmd/linuxkit/initrd/initrd.go:168 +0x4f fp=0xc000649028 sp=0xc000648fe0 pc=0x7f0045c84b3f
io.copyBuffer(0x7f00470a3560, 0xc0001a8270, 0x7f00470a3080, 0xc0000c6480, 0xc08bcfc000, 0x8000, 0x8000, 0xc000649150, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:404 +0x203 fp=0xc000649098 sp=0xc000649028 pc=0x7f00456cfce3
io.Copy(0x7f00470a3560, 0xc0001a8270, 0x7f00470a3080, 0xc0000c6480, 0x0, 0x0, 0x2)
	/usr/lib/go/src/io/io.go:364 +0x5c fp=0xc0006490f8 sp=0xc000649098 pc=0x7f00456cf9ac
github.com/linuxkit/linuxkit/src/cmd/linuxkit/initrd.copyTarEntry(0xc0001a8270, 0xc08bce2620, 0x7f00470a3080, 0xc0000c6480, 0x13, 0x0, 0x0)
	/go/src/github.com/linuxkit/linuxkit/src/cmd/linuxkit/initrd/initrd.go:87 +0x28d fp=0xc0006491b0 sp=0xc0006490f8 pc=0x7f0045c841ed
github.com/linuxkit/linuxkit/src/cmd/linuxkit/initrd.CopySplitTar(0xc0001a8270, 0xc0000c6480, 0x1, 0x7f004268ac90, 0x7f00456c09b0, 0xc0006492b0, 0xc0006492c0, 0x10, 0x7f0046ce9700, 0x7f0046ce9700, ...)
	/go/src/github.com/linuxkit/linuxkit/src/cmd/linuxkit/initrd/initrd.go:144 +0x1d4 fp=0xc000649250 sp=0xc0006491b0 pc=0x7f0045c84484
github.com/linuxkit/linuxkit/src/cmd/linuxkit/moby.tarToInitrd(0x7f00470a6760, 0xc0000b2030, 0x7f0045736a31, 0xc000230310, 0xc000000300, 0xc0000ba1e0, 0x7f004567e473, 0x7f0046603332, 0x7fffa404b65e, 0xd, ...)
	/go/src/github.com/linuxkit/linuxkit/src/cmd/linuxkit/moby/output.go:272 +0x1cb fp=0xc000649340 sp=0xc000649250 pc=0x7f0045c9bfbb
github.com/linuxkit/linuxkit/src/cmd/linuxkit/moby.glob..func2(0xc0000ac360,
0x2d, 0x7f00470a6760, 0xc0000b2030, 0x400, 0x1, 0xc000649460, 0x7f00457612a1)
	/go/src/github.com/linuxkit/linuxkit/src/cmd/linuxkit/moby/output.go:48 +0x4f fp=0xc0006493e8 sp=0xc000649340 pc=0x7f0045ca16ef
github.com/linuxkit/linuxkit/src/cmd/linuxkit/moby.Formats(0xc0000ac360, 0x2d, 0xc000230310, 0xe, 0xc00009b380, 0x1, 0x1, 0x400, 0x1, 0x0, ...)
	/go/src/github.com/linuxkit/linuxkit/src/cmd/linuxkit/moby/output.go:260 +0x29a fp=0xc0006494a8 sp=0xc0006493e8 pc=0x7f0045c9bd0a
main.build(0xc0000b8020, 0x7, 0x7)
	/go/src/github.com/linuxkit/linuxkit/src/cmd/linuxkit/build.go:220 +0x116c fp=0xc000649f00 sp=0xc0006494a8 pc=0x7f00465a936c
main.main()
	/go/src/github.com/linuxkit/linuxkit/src/cmd/linuxkit/main.go:121 +0x417 fp=0xc000649f98 sp=0xc000649f00 pc=0x7f00465af127
runtime.main()
	/usr/lib/go/src/runtime/proc.go:201 +0x20f fp=0xc000649fe0 sp=0xc000649f98 pc=0x7f004569982f
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000649fe8 sp=0xc000649fe0 pc=0x7f00456c5641

goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
	/usr/lib/go/src/runtime/sigqueue.go:139 +0x9e
os/signal.loop()
	/usr/lib/go/src/os/signal/signal_unix.go:23 +0x24
created by os/signal.init.0
	/usr/lib/go/src/os/signal/signal_unix.go:29 +0x43

goroutine 9 [IO wait]:
internal/poll.runtime_pollWait(0x7f004268af00, 0x72, 0xc000064a88)
	/usr/lib/go/src/runtime/netpoll.go:173 +0x68
internal/poll.(*pollDesc).wait(0xc000260418, 0x72, 0xffffffffffffff00, 0x7f00470a8fe0, 0x7f0048237ac0)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:85 +0x9c
internal/poll.(*pollDesc).waitRead(0xc000260418, 0xc0003bc000, 0x1000, 0x1000)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:90 +0x3f
internal/poll.(*FD).Read(0xc000260400, 0xc0003bc000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/internal/poll/fd_unix.go:169 +0x17b
net.(*netFD).Read(0xc000260400, 0xc0003bc000, 0x1000, 0x1000, 0xc000064b70, 0x7f00456c21f0, 0xc000000300)
	/usr/lib/go/src/net/fd_unix.go:202 +0x51
net.(*conn).Read(0xc0000b2a20, 0xc0003bc000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:177 +0x6a
net/http.(*persistConn).Read(0xc000264360, 0xc0003bc000, 0x1000, 0x1000, 0xc000064c70, 0x7f0045671335, 0xc00008a4e0)
	/usr/lib/go/src/net/http/transport.go:1497 +0x77
bufio.(*Reader).fill(0xc00026fce0)
	/usr/lib/go/src/bufio/bufio.go:100 +0x111
bufio.(*Reader).Peek(0xc00026fce0, 0x1, 0x0, 0x0, 0x1, 0xc00008a420, 0x0)
	/usr/lib/go/src/bufio/bufio.go:132 +0x41
net/http.(*persistConn).readLoop(0xc000264360)
	/usr/lib/go/src/net/http/transport.go:1645 +0x1a4
created by net/http.(*Transport).dialConn
	/usr/lib/go/src/net/http/transport.go:1338 +0x943

goroutine 10 [select]:
net/http.(*persistConn).writeLoop(0xc000264360)
	/usr/lib/go/src/net/http/transport.go:1885 +0x115
created by net/http.(*Transport).dialConn
	/usr/lib/go/src/net/http/transport.go:1339 +0x968

goroutine 23 [IO wait]:
internal/poll.runtime_pollWait(0x7f004268ae30, 0x72, 0xc0000d1a88)
	/usr/lib/go/src/runtime/netpoll.go:173 +0x68
internal/poll.(*pollDesc).wait(0xc000248298, 0x72, 0xffffffffffffff00, 0x7f00470a8fe0, 0x7f0048237ac0)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:85 +0x9c
internal/poll.(*pollDesc).waitRead(0xc000248298, 0xc000018000, 0x1000, 0x1000)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:90 +0x3f
internal/poll.(*FD).Read(0xc000248280, 0xc000018000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/internal/poll/fd_unix.go:169 +0x17b
net.(*netFD).Read(0xc000248280, 0xc000018000, 0x1000, 0x1000, 0xc0000d1b70, 0x7f00456c21f0, 0xc000000300)
	/usr/lib/go/src/net/fd_unix.go:202 +0x51
net.(*conn).Read(0xc00000e050, 0xc000018000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:177 +0x6a
net/http.(*persistConn).Read(0xc00024a120, 0xc000018000, 0x1000, 0x1000, 0xc0000d1c70, 0x7f0045671335, 0xc0003b64e0)
	/usr/lib/go/src/net/http/transport.go:1497 +0x77
bufio.(*Reader).fill(0xc000080360)
	/usr/lib/go/src/bufio/bufio.go:100 +0x111
bufio.(*Reader).Peek(0xc000080360, 0x1, 0x0, 0x0, 0x1, 0xc0003b6420, 0x0)
	/usr/lib/go/src/bufio/bufio.go:132 +0x41
net/http.(*persistConn).readLoop(0xc00024a120)
	/usr/lib/go/src/net/http/transport.go:1645 +0x1a4
created by net/http.(*Transport).dialConn
	/usr/lib/go/src/net/http/transport.go:1338 +0x943

goroutine 24 [select]:
net/http.(*persistConn).writeLoop(0xc00024a120)
	/usr/lib/go/src/net/http/transport.go:1885 +0x115
created by net/http.(*Transport).dialConn
	/usr/lib/go/src/net/http/transport.go:1339 +0x968

goroutine 26 [IO wait]:
internal/poll.runtime_pollWait(0x7f004268ad60, 0x72, 0xc0000cda88)
	/usr/lib/go/src/runtime/netpoll.go:173 +0x68
internal/poll.(*pollDesc).wait(0xc00033a318, 0x72, 0xffffffffffffff00, 0x7f00470a8fe0, 0x7f0048237ac0)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:85 +0x9c
internal/poll.(*pollDesc).waitRead(0xc00033a318, 0xc0003a4000, 0x1000, 0x1000)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:90 +0x3f
internal/poll.(*FD).Read(0xc00033a300, 0xc0003a4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/internal/poll/fd_unix.go:169 +0x17b
net.(*netFD).Read(0xc00033a300, 0xc0003a4000, 0x1000, 0x1000, 0x0, 0x0, 0x7f00465f8010)
	/usr/lib/go/src/net/fd_unix.go:202 +0x51
net.(*conn).Read(0xc00000e070, 0xc0003a4000, 0x1000, 0x1000, 0x0,
0x0, 0x0)
	/usr/lib/go/src/net/net.go:177 +0x6a
net/http.(*persistConn).Read(0xc000480120, 0xc0003a4000, 0x1000, 0x1000, 0xc000480000, 0xc000480120, 0x0)
	/usr/lib/go/src/net/http/transport.go:1497 +0x77
bufio.(*Reader).fill(0xc0000b4480)
	/usr/lib/go/src/bufio/bufio.go:100 +0x111
bufio.(*Reader).Peek(0xc0000b4480, 0x1, 0x2, 0x0, 0x0, 0xc00008acc0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:132 +0x41
net/http.(*persistConn).readLoop(0xc000480120)
	/usr/lib/go/src/net/http/transport.go:1645 +0x1a4
created by net/http.(*Transport).dialConn
	/usr/lib/go/src/net/http/transport.go:1338 +0x943

goroutine 27 [select]:
net/http.(*persistConn).writeLoop(0xc000480120)
	/usr/lib/go/src/net/http/transport.go:1885 +0x115
created by net/http.(*Transport).dialConn
	/usr/lib/go/src/net/http/transport.go:1339 +0x968
"
[ E48 ] EIF building error. Such error appears when trying to build an EIF file. In this case, the error backtrace provides detailed information on the failure reason.
```

**Comment by petreeftime** [comment]
I've reformatted the code to be slightly more readable.

The main error seems to be: `fatal error: runtime: out of memory`.  My initial thought is that the 2 images above are large and linuxkit processes then in-memory, leading to an out-of-memory state for the process.

**Comment by open-contracts** [comment]
Thank you! That seems to be correct. Switching to a larger instance avoided this error!

**Comment by alcioa** [comment]
@Jonas-Metzger have you found the above workaround useful? Asking if issue is still relevant.

**Comment by open-contracts** [comment]
@alcioa yes! thank you. @Jonas-Metzger is my other account.
